name: Build and deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Create production package.json
      run: npm prune --production --omit=devDependencies,scripts && cp package.json production/ && mv production/package.json production/production-package.json
    - name: Copy files to production folder
      run: |
        cp -R dist/ production/
        cp vercel.json production/
    - name: Commit and push changes
      uses: EndBug/add-and-commit@v7
      with:
        message: "Build and deploy"
        add: "production/*"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: production