name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install jq
        run: sudo apt-get update && sudo apt-get -y install jq
      - name: Build and Deploy
        run: |
          mkdir -p production
          cp -R dist/* production/
          cat package.json | jq -c 'del(.devDependencies, .scripts)' > production/package.json
          cp vercel.json production/
          git config user.email "kkp785216@gmail.com"
          git config user.name "Krishna Kumar Prajapati"
          git add production
          git commit -m "Build production assets"
          git push origin HEAD:production
